# Generated by Django 4.2.2 on 2024-11-14 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=64)),
                ('business_type', models.CharField(max_length=50)),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_verified', models.BooleanField(default=False)),
                ('subdirectory', models.SlugField(max_length=64, unique=True)),
                ('navigation_style', models.CharField(choices=[('minimal', 'Minimal'), ('centered', 'Centered'), ('split', 'Split')], default='minimal', max_length=20)),
                ('footer_style', models.CharField(choices=[('detailed', 'Detailed'), ('minimal', 'Minimal'), ('simple', 'Simple')], default='minimal', max_length=20)),
                ('show_gallery', models.BooleanField(default=True)),
                ('show_testimonials', models.BooleanField(default=True)),
                ('show_social_feed', models.BooleanField(default=True)),
                ('show_hours', models.BooleanField(default=True)),
                ('show_map', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#4F46E5', max_length=7)),
                ('secondary_color', models.CharField(default='#1F2937', max_length=7)),
                ('font_heading', models.CharField(default='Inter', max_length=50)),
                ('font_body', models.CharField(default='Inter', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CuisineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SubPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('menu', 'Menu'), ('services', 'Services'), ('products', 'Products'), ('gallery', 'Gallery'), ('contact', 'Contact')], max_length=10)),
                ('hero_layout', models.CharField(choices=[('full-image', 'Full Image'), ('offset-left', 'Image with Left Text'), ('offset-right', 'Image with Right Text'), ('banner-slider', 'Banner Slider')], default='full-image', max_length=20)),
                ('hero_heading', models.CharField(blank=True, max_length=200)),
                ('hero_subheading', models.TextField(blank=True)),
                ('hero_button_text', models.CharField(blank=True, max_length=50)),
                ('hero_button_link', models.CharField(blank=True, max_length=200)),
                ('hero_text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10)),
                ('hero_text_color', models.CharField(default='#000000', max_length=7)),
                ('hero_subtext_color', models.CharField(default='#6B7280', max_length=7)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpages', to='restaurants.business')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('business', 'page_type')},
            },
        ),
        migrations.CreateModel(
            name='SpecialsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specials_content', to='restaurants.subpage')),
            ],
        ),
        migrations.CreateModel(
            name='SideOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_premium', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_options', to='restaurants.course')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('display_style', models.CharField(choices=[('grid', 'Grid Layout'), ('list', 'List Layout'), ('cards', 'Card Layout')], default='grid', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurants.business')),
                ('subpage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_content', to='restaurants.subpage')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_uploads/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/%Y/%m/%d/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='events_content', to='restaurants.subpage')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('events_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='restaurants.eventspage')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='restaurants.menu'),
        ),
        migrations.AddField(
            model_name='business',
            name='cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisines', to='restaurants.cuisinecategory'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='user_favorite',
            field=models.ManyToManyField(blank=True, related_name='regular', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('history', models.TextField(blank=True, null=True)),
                ('team_members', models.TextField(blank=True, null=True)),
                ('subpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_content', to='restaurants.subpage')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/')),
                ('description', models.TextField(default='', max_length=200)),
                ('date_added', models.DateField(auto_now=True)),
                ('is_special', models.BooleanField(default=False)),
                ('included_sides', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurants.course')),
                ('favorites', models.ManyToManyField(blank=True, related_name='user_favorite', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurants.menu')),
            ],
            options={
                'unique_together': {('course', 'name')},
            },
        ),
    ]
