# Generated by Django 4.2.2 on 2024-11-14 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_business_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='cuisine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuisines', to='restaurants.cuisinecategory'),
        ),
    ]
