# Generated by Django 4.2.2 on 2024-10-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
