# Generated by Django 4.2.2 on 2024-11-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_business_cuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='business',
            name='cuisine',
            field=models.ManyToManyField(blank=True, related_name='cuisines', to='restaurants.cuisinecategory'),
        ),
    ]
