# Generated by Django 4.2.2 on 2024-11-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_business_cuisine_business_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpage',
            name='show_hero_heading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subpage',
            name='show_hero_subheading',
            field=models.BooleanField(default=False),
        ),
    ]
