# Generated by Django 4.2.2 on 2024-10-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_kitchen_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='foo',
        ),
    ]
