# Generated by Django 4.2.2 on 2024-10-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
