# Generated by Django 4.2.2 on 2024-10-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_kitchen_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='zip_code',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
