# Generated by Django 4.2.2 on 2024-10-11 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_delete_foo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cuisine_categories',
            new_name='CuisineCategory',
        ),
    ]
