# Generated by Django 4.2.2 on 2024-10-11 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_rename_cuisine_categories_cuisinecategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu_course',
            new_name='MenuCourse',
        ),
    ]
