# Generated by Django 4.2.2 on 2024-10-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_kitchen_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='country',
        ),
    ]
