# Generated by Django 4.2.2 on 2024-11-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_subpage_primary_color_subpage_secondary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='hover_color',
            field=models.CharField(default='#9333EA', max_length=7),
        ),
    ]
