# Generated by Django 4.2.2 on 2024-10-23 19:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_kitchen_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
