# Generated by Django 4.2.2 on 2024-11-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_business_hover_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpage',
            name='hover_color',
            field=models.CharField(default='#9333EA', max_length=7),
        ),
    ]
