# Generated by Django 4.2.2 on 2024-10-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_kitchen_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='subidrectory',
            field=models.SlugField(default=21, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
