# Generated by Django 4.2.2 on 2024-11-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_business_text_color_subpage_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpage',
            name='font_body',
            field=models.CharField(default='Inter', max_length=50),
        ),
        migrations.AddField(
            model_name='subpage',
            name='font_heading',
            field=models.CharField(default='Inter', max_length=50),
        ),
    ]
