# Generated by Django 4.2.2 on 2024-11-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_combine_font_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpage',
            name='hero_font',
            field=models.CharField(default='Inter', max_length=50),
        ),
        migrations.AddField(
            model_name='subpage',
            name='hero_heading_size',
            field=models.CharField(default='text-3xl', max_length=20),
        ),
        migrations.AddField(
            model_name='subpage',
            name='hero_subheading_size',
            field=models.CharField(default='text-lg', max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='main_font',
            field=models.CharField(default='Inter', max_length=50),
        ),
    ]
