# Generated by Django 4.2.2 on 2024-10-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_remove_dish_recipe_owner_menu_event_dish_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='layout',
            field=models.CharField(choices=[('default', 'Default Layout'), ('modern', 'Modern Layout'), ('classic', 'Classic Layout')], default='default', max_length=20),
        ),
    ]
