# Generated by Django 4.2.2 on 2024-10-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_remove_kitchen_courses_image_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subpage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='kitchen',
        ),
        migrations.AddField(
            model_name='dish',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='subpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_content', to='restaurants.subpage'),
        ),
        migrations.AddField(
            model_name='subpage',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subpage',
            name='page_type',
            field=models.CharField(choices=[('about', 'About Us'), ('menu', 'Menu'), ('events', 'Events'), ('specials', 'Specials')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='SpecialsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specials_content', to='restaurants.subpage')),
            ],
        ),
        migrations.CreateModel(
            name='EventsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='events_content', to='restaurants.subpage')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('history', models.TextField(blank=True, null=True)),
                ('team_members', models.TextField(blank=True, null=True)),
                ('subpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_content', to='restaurants.subpage')),
            ],
        ),
        migrations.RemoveField(
            model_name='subpage',
            name='content',
        ),
        migrations.AddField(
            model_name='event',
            name='events_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='restaurants.eventspage'),
            preserve_default=False,
        ),
    ]
