# Generated by Django 4.2.2 on 2024-11-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_rename_hero_font_subpage_hero_heading_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpage',
            name='banner_2_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_2_heading_font',
            field=models.CharField(default='Inter', max_length=100),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_2_heading_size',
            field=models.CharField(default='text-4xl', max_length=20),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_2_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_2_pages', to='restaurants.image'),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_2_subheading',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_2_subheading_font',
            field=models.CharField(default='Inter', max_length=100),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_2_subheading_size',
            field=models.CharField(default='text-xl', max_length=20),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_3_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_3_heading_font',
            field=models.CharField(default='Inter', max_length=100),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_3_heading_size',
            field=models.CharField(default='text-4xl', max_length=20),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_3_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_3_pages', to='restaurants.image'),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_3_subheading',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_3_subheading_font',
            field=models.CharField(default='Inter', max_length=100),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_3_subheading_size',
            field=models.CharField(default='text-xl', max_length=20),
        ),
        migrations.AddField(
            model_name='subpage',
            name='show_banner_2_heading',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subpage',
            name='show_banner_2_subheading',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subpage',
            name='show_banner_3_heading',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subpage',
            name='show_banner_3_subheading',
            field=models.BooleanField(default=True),
        ),
    ]
