# Generated by Django 4.2.2 on 2024-11-30 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_subpage_banner_2_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpage',
            name='banner_2_image',
        ),
        migrations.RemoveField(
            model_name='subpage',
            name='banner_3_image',
        ),
    ]
