# Generated by Django 4.2.2 on 2024-12-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_remove_subpage_banner_2_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpage',
            name='banner_2_heading_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_2_subheading_color',
            field=models.CharField(default='#6B7280', max_length=7),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_3_heading_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_3_subheading_color',
            field=models.CharField(default='#6B7280', max_length=7),
        ),
    ]
