# Generated by Django 4.2.2 on 2024-10-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image_url',
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/'),
        ),
    ]
