# Generated by Django 4.2.2 on 2024-12-04 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_subpage_banner_2_button_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subpage',
            old_name='hero_text_color',
            new_name='hero_heading_color',
        ),
        migrations.RenameField(
            model_name='subpage',
            old_name='hero_subtext_color',
            new_name='hero_subheading_color',
        ),
    ]
