# Generated by Django 4.2.2 on 2024-10-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_handle_duplicate_dishes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('course', 'name')},
        ),
    ]
