# Generated by Django 4.2.2 on 2024-12-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_rename_hero_text_color_subpage_hero_heading_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpage',
            name='banner_2_button_bg_color',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_2_button_size',
            field=models.CharField(default='md', max_length=20),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_2_button_text_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_3_button_bg_color',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_3_button_size',
            field=models.CharField(default='md', max_length=20),
        ),
        migrations.AddField(
            model_name='subpage',
            name='banner_3_button_text_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='subpage',
            name='hero_button_bg_color',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AddField(
            model_name='subpage',
            name='hero_button_size',
            field=models.CharField(default='md', max_length=20),
        ),
        migrations.AddField(
            model_name='subpage',
            name='hero_button_text_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
