# Generated by Django 4.2.2 on 2024-10-31 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_alter_dish_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='included_sides',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SideOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_premium', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_options', to='restaurants.course')),
            ],
        ),
    ]
