# Generated by Django 4.2.2 on 2024-12-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_subpage_banner_2_button_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpage',
            name='show_banner_2_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subpage',
            name='show_banner_3_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subpage',
            name='show_hero_button',
            field=models.BooleanField(default=False),
        ),
    ]
