# Generated by Django 4.2.2 on 2024-11-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_course_note_dish_included_sides_sideoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
