# Generated by Django 4.2.2 on 2024-12-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_subpage_show_banner_2_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpage',
            name='hero_size',
            field=models.CharField(choices=[('full-screen', 'Full Screen'), ('half-screen', 'Half Screen')], default='full-screen', max_length=20),
        ),
    ]
