# Generated by Django 4.2.2 on 2024-12-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_subpage_hero_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpage',
            name='hero_size',
            field=models.CharField(choices=[('full-screen', 'Full Screen'), ('half-screen', 'Half Screen')], default='full-width', max_length=20),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='page_type',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('menu', 'Menu'), ('services', 'Services'), ('products', 'Products'), ('gallery', 'Gallery'), ('contact', 'Contact'), ('specials', 'Specials')], max_length=10),
        ),
    ]
