# Generated by Django 4.2.2 on 2024-11-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_kitchen_font_body_kitchen_font_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpage',
            name='hero_button_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subpage',
            name='hero_button_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subpage',
            name='hero_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subpage',
            name='hero_layout',
            field=models.CharField(choices=[('offset-left', 'Image with Left Text'), ('offset-right', 'Image with Right Text'), ('full-image', 'Full Image'), ('banner-slider', 'Banner Slider')], default='offset-left', max_length=20),
        ),
        migrations.AddField(
            model_name='subpage',
            name='hero_subheading',
            field=models.TextField(blank=True),
        ),
    ]
