# Generated by Django 4.2.2 on 2024-11-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0023_subpage_hero_subtext_color_subpage_hero_text_align_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='hero_style',
            field=models.CharField(choices=[('image-full', 'Full Screen Image'), ('split', 'Split Layout'), ('minimal', 'Minimal Text')], default='offset-left', max_length=20),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='layout',
            field=models.CharField(choices=[('minimal', 'Minimal Layout'), ('modern', 'Modern Layout'), ('classic', 'Classic Layout')], default='minimal', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subpage',
            unique_together={('kitchen', 'page_type')},
        ),
    ]
