# Generated by Django 4.2.2 on 2024-12-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0023_alter_subpage_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpage',
            name='page_type',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('menu', 'Menu'), ('services', 'Services'), ('products', 'Products'), ('gallery', 'Gallery'), ('contact', 'Contact'), ('specials', 'Specials'), ('events', 'Events'), ('merch', 'Merch'), ('contact', 'Contact'), ('testimonials', 'Testimonials')], max_length=14),
        ),
    ]
