# Generated by Django 4.2.2 on 2024-11-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0024_alter_kitchen_hero_style_alter_kitchen_layout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpage',
            name='page_type',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About Us'), ('menu', 'Menu'), ('events', 'Events'), ('specials', 'Specials')], max_length=10),
        ),
    ]
