# Generated by Django 4.2.2 on 2024-11-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0025_alter_subpage_page_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='layout',
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='hero_style',
            field=models.CharField(choices=[('image-full', 'Full Screen Image'), ('offset-left', 'Offset Left'), ('offset-right', 'Offset Right'), ('banner-slider', 'Banner Slider')], default='offset-left', max_length=20),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='navigation_style',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('centered', 'Centered'), ('split', 'Split')], default='minimal', max_length=20),
        ),
    ]
