# Generated by Django 4.2.2 on 2024-11-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0026_remove_kitchen_layout_alter_kitchen_hero_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='hero_style',
            field=models.CharField(choices=[('image-full', 'Full Screen Image'), ('offset-left', 'Offset Left'), ('offset-right', 'Offset Right'), ('banner-slider', 'Banner Slider')], default='image-full', max_length=20),
        ),
    ]
