# Generated by Django 5.0 on 2025-01-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0026_remove_cuisine_from_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cuisine',
            field=models.ManyToManyField(blank=True, related_name='business_cuisines', to='restaurants.cuisinecategory'),
        ),
    ]
