# Generated by Django 5.0 on 2025-01-13 18:10

from django.db import migrations

def forward_func(apps, schema_editor):
    Business = apps.get_model('restaurants', 'Business')
    # Clear any existing cuisine relationships
    for business in Business.objects.all():
        business.cuisine.clear()

class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0027_business_cuisine'),
    ]

    operations = [
        migrations.RunPython(forward_func),
        migrations.RemoveField(
            model_name='business',
            name='cuisine',
        ),
    ]
