# Generated by Django 5.0 on 2025-01-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0029_dish_happy_hour_dish_happy_hour_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
