# Generated by Django 5.0 on 2025-01-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0031_event_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
