# Generated by Django 5.0 on 2025-01-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0032_remove_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
