# Generated by Django 5.0 on 2025-01-21 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0033_business_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(choices=[('grid', 'Grid Layout'), ('list', 'List Layout'), ('cards', 'Card Layout')], default='grid', max_length=20)),
                ('welcome_title', models.CharField(blank=True, max_length=200, null=True)),
                ('welcome_message', models.TextField(blank=True, null=True)),
                ('show_welcome', models.BooleanField(default=False)),
                ('show_affiliates', models.BooleanField(default=False)),
                ('show_newsfeed', models.BooleanField(default=False)),
                ('show_upcoming_event', models.BooleanField(default=False)),
                ('show_daily_special', models.BooleanField(default=False)),
                ('show_featured_service', models.BooleanField(default=False)),
                ('show_featured_product', models.BooleanField(default=False)),
                ('subpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_content', to='restaurants.subpage')),
            ],
        ),
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_feed', to='restaurants.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='user_liked', to=settings.AUTH_USER_MODEL)),
                ('news_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to='restaurants.newsfeed')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='restaurants.newspost')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('subpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='products_content', to='restaurants.subpage')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('featured', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('products_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restaurants.productspage')),
            ],
        ),
    ]
