# Generated by Django 5.0 on 2025-01-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0035_business_affiliates'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_map',
            field=models.BooleanField(default=False),
        ),
    ]
