# Generated by Django 5.0 on 2025-01-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0036_homepage_show_hours_homepage_show_map'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutuspage',
            options={'verbose_name': 'About Us Page', 'verbose_name_plural': 'About Us Pages'},
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='core_values',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='mission_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='show_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='show_mission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='show_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='show_values',
            field=models.BooleanField(default=False),
        ),
    ]
