# Generated by Django 5.0 on 2025-01-28 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0039_contactmessage_contactpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyspecial',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='dailyspecial',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restaurants.business'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
