# Generated by Django 5.0 on 2025-01-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0041_remove_null_from_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspage',
            name='show_description',
            field=models.BooleanField(default=False),
        ),
    ]
