# Generated by Django 5.0 on 2025-01-29 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0044_remove_product_image_remove_service_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='restaurants.business'),
        ),
    ]
