# Generated by Django 5.0 on 2025-01-30 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0046_remove_null_business_from_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('show_description', models.BooleanField(default=False)),
                ('subpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_content', to='restaurants.subpage')),
            ],
        ),
    ]
