# Generated by Django 5.0 on 2026-01-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0047_gallerypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='show_description',
            field=models.BooleanField(default=False, verbose_name='Show Description'),
        ),
    ]
